/*PRIMARY KEYS*/
ALTER TABLE Category ADD PRIMARY KEY(CategoryID);
ALTER TABLE SalesRep ADD PRIMARY KEY(SalesRepID);
ALTER TABLE Shop ADD PRIMARY KEY(ShopID);
ALTER TABLE Publisher ADD PRIMARY KEY(PublisherID);
ALTER TABLE Book ADD PRIMARY KEY(BookID);
ALTER TABLE ShopOrder ADD PRIMARY KEY(ShopOrderID);
ALTER TABLE OrderLine ADD PRIMARY KEY(ShopOrderID,BookID);

/*FOREIGN KEYS*/
ALTER TABLE Book ADD FOREIGN KEY (CategoryID) REFERENCES Category ON DELETE RESTRICT;
ALTER TABLE Book ADD FOREIGN KEY (PublisherID) REFERENCES Publisher ON DELETE RESTRICT;
ALTER TABLE ShopOrder ADD FOREIGN KEY (ShopID) REFERENCES Shop ON DELETE RESTRICT;
ALTER TABLE ShopOrder ADD FOREIGN KEY (SalesRepID) REFERENCES SalesRep ON DELETE RESTRICT;
ALTER TABLE OrderLine ADD FOREIGN KEY (ShopOrderID) REFERENCES ShopOrder ON DELETE RESTRICT;
ALTER TABLE OrderLine ADD FOREIGN KEY (BookID) REFERENCES Book ON DELETE RESTRICT;

/*ONLY ALLOW SPECIFIC VALUES FOR CategoryType*/
ALTER TABLE Category
	ADD CONSTRAINT chk_categ_type 
	CHECK (categoryType='fiction' OR categoryType='Non-fiction');

/*PREVENT Name FROM ACCEPTING EMPTY VALUE*/
ALTER TABLE Category
	ADD CONSTRAINT chk_empty_val
	CHECK (name <> '');

/*PREVENT NEGATIVE VALUES FOR Price*/
ALTER TABLE Book
	ADD CONSTRAINT chk_price
	CHECK (Price>0);

/*PREVENT OrderDate BEING LATER THAN CURRENT DATE*/
ALTER TABLE ShopOrder
	ADD CONSTRAINT chk_date
	CHECK (OrderDate<= CURRENT_DATE);

/*PREVENT NEGATIVE VALUES FOR Quantity*/
ALTER TABLE OrderLine
	ADD CONSTRAINT chk_qty
	CHECK (Quantity>0);

/*PREVENT NEGATIVE VALUES FOR UnitSellingPrice*/
ALTER TABLE OrderLine
	ADD CONSTRAINT chk_sell_price
	CHECK (UnitSellingPrice>=0);

/*MAKE Name UNIQUE*/
ALTER TABLE Category
	ADD CONSTRAINT unique_name
	UNIQUE (name);

/*PREVENT Name FROM BEING NULL*/
ALTER TABLE Category
	ALTER COLUMN Name
	SET NOT NULL;

/*PREVENT Name FROM BEING NULL*/
ALTER TABLE SalesRep
	ALTER COLUMN Name
	SET NOT NULL;

/*PREVENT Name FROM ACCEPTING EMPTY VALUE*/
ALTER TABLE SalesRep
	ADD CONSTRAINT chk_empty_val
	CHECK (name <> '');
	
/*PREVENT Name FROM BEING NULL*/
ALTER TABLE Shop
	ALTER COLUMN Name
	SET NOT NULL;

/*PREVENT Name FROM ACCEPTING EMPTY VALUE*/
ALTER TABLE Shop
	ADD CONSTRAINT chk_empty_val
	CHECK (name <> '');

/*PREVENT Name FROM BEING NULL*/
ALTER TABLE Publisher
	ALTER COLUMN Name
	SET NOT NULL;

/*PREVENT Name FROM ACCEPTING EMPTY VALUE*/
ALTER TABLE Publisher
	ADD CONSTRAINT chk_empty_val
	CHECK (name <> '');

/*PREVENT Title FROM BEING NULL*/
ALTER TABLE Book
	ALTER COLUMN Title
	SET NOT NULL;
	
/*PREVENT Name FROM ACCEPTING EMPTY VALUE*/
ALTER TABLE Book
	ADD CONSTRAINT chk_empty_val
	CHECK (title <> '');

/*PREVENT OrderDate FROM BEING NULL*/
ALTER TABLE ShopOrder
	ALTER COLUMN orderdate
	SET NOT NULL;
