SELECT NAME as categ_name,COUNT(TITLE)as book_count, round(avg(price), 2)
	as avg_price FROM BOOK FULL JOIN CATEGORY ON CATEGORY.CATEGORYID = BOOK.CATEGORYID 
GROUP BY CATEGORY.CATEGORYID ORDER BY CATEGORY.CATEGORYID

SELECT DISTINCT(SELECT COUNT(CATEGORY.CATEGORYID) as categ_count FROM CATEGORY),
	COUNT(BOOK.TITLE) as book_count, SUM(BOOK.PRICE) as price_sum FROM BOOK